name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install goss
      run: |
        mkdir -p ~/bin
        curl -fsSL https://goss.rocks/install | GOSS_VER=v0.3.6 GOSS_DST=~/bin sh
    - name: Build docker image
      run: docker build . -t luotaoruby/jenkins-ssh-slave
    - name: Run goss tests
      run: GOSS_PATH="$HOME/bin/goss" /home/runner/bin/dgoss run -t luotaoruby/jenkins-ssh-slave
    - name: Publish to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: luotaoruby/jenkins-ssh-slave
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

